### ISSUE TITLE
Add a MediawikiOAuthenticator

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/oauthenticator#21]
Hello! I've been using https://github.com/yuvipanda/mwoauthenticator at Wikimedia's test installation, and would like to get it merged 'upstream' (here). Is this repo accepting new such authenticators, or should it continue to live in a separate repo? If this is acceptable here I'll do the work in integrating it and send a PR. Wanted to ask before I expend effort :)

Thanks!

**Comment by minrk** [comment]
It's unclear to me what exactly the scope of this repo is in terms of new authenticators. I didn't originally intend for it to be anything more than GitHub, but we've added a couple already. I'd say it's fine to add this, if you would prefer it to be bundled as part of this repo, but you don't need to if you are happy maintaining your own package. Since CI for OAuth is hard, we'll have to rely on you for testing/maintaining it.

**Comment by yuvipanda** [comment]
I'm happy to be maintaining it :) I'll work on a PR to move that into this repo! Thanks :)
